name: sylt_parser
description: A library for parsing timecoded lyrics data from SYLT-frames encoded in mp3 files. (SYnchronized Lyrics/Text)
version: 0.1.1
repository: https://github.com/Movinghead333/sylt_parser

environment:
  sdk: ^3.1.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
